<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResourceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ids must not be changed
        DB::table("resource")->insert([
            [
                "id" => 1,
                "name" => "Dirt",
                "marketPrice" => 0.25,
                "levelToMine" => 1,
                "timeToMine" => 60,
                "mineQuantity" => 5,
            ],
            [
                "id" => 2,
                "name" => "Stone",
                "marketPrice" => 0.75,
                "levelToMine" => 1,
                "timeToMine" => 60,
                "mineQuantity" => 4,
            ],
            [
                "id" => 3,
                "name" => "Sand",
                "marketPrice" => 2.15,
                "levelToMine" => 1,
                "timeToMine" => 90,
                "mineQuantity" => 3.5,
            ],
            [
                "id" => 4,
                "name" => "Gravel",
                "marketPrice" => 2.15,
                "levelToMine" => 1,
                "timeToMine" => 90,
                "mineQuantity" => 3.5,
            ],
            [
                "id" => 5,
                "name" => "Wood",
                "marketPrice" => 4,
                "levelToMine" => 1,
                "timeToMine" => 120,
                "mineQuantity" => 5,
            ],
            [
                "id" => 6,
                "name" => "Water",
                "marketPrice" => 0.15,
                "levelToMine" => 1,
                "timeToMine" => 30,
                "mineQuantity" => 3,
            ],
            [
                "id" => 7,
                "name" => "Coal",
                "marketPrice" => 50,
                "levelToMine" => 2,
                "timeToMine" => 240,
                "mineQuantity" => 1,
            ],
            [
                "id" => 8,
                "name" => "Iron",
                "marketPrice" => 130,
                "levelToMine" => 2,
                "timeToMine" => 480,
                "mineQuantity" => 1,
            ],
            [
                "id" => 9,
                "name" => "Marble",
                "marketPrice" => 90,
                "levelToMine" => 2,
                "timeToMine" => 600,
                "mineQuantity" => 0.5,
            ],
            [
                "id" => 10,
                "name" => "Magma",
                "marketPrice" => 90,
                "levelToMine" => 3,
                "timeToMine" => 180,
                "mineQuantity" => 0.5,
            ],
            [
                "id" => 11,
                "name" => "Gold",
                "marketPrice" => 155,
                "levelToMine" => 3,
                "timeToMine" => 600,
                "mineQuantity" => 1.25,
            ],
            [
                "id" => 12,
                "name" => "Diamond",
                "marketPrice" => 500,
                "levelToMine" => 4,
                "timeToMine" => 1200,
                "mineQuantity" => 1,
            ],
            [
                "id" => 13,
                "name" => "Uranium",
                "marketPrice" => 525,
                "levelToMine" => 4,
                "timeToMine" => 2100,
                "mineQuantity" => 2,
            ],
            [
                "id" => 14,
                "name" => "Oil",
                "marketPrice" => 320,
                "levelToMine" => 3,
                "timeToMine" => 480,
                "mineQuantity" => 0.5,
            ],
            [
                "id" => 15,
                "name" => "Emerald",
                "marketPrice" => 900,
                "levelToMine" => 5,
                "timeToMine" => 1800,
                "mineQuantity" => 1,
            ],
            [
                "id" => 16,
                "name" => "Nickel",
                "marketPrice" => 450,
                "levelToMine" => 4,
                "timeToMine" => 2700,
                "mineQuantity" => 3.5,
            ],
            [
                "id" => 17,
                "name" => "Antimatter",
                "marketPrice" => 2500000,
                "levelToMine" => 6,
                "timeToMine" => 14400,
                "mineQuantity" => 0.01,
            ],
            [
                "id" => 18,
                "name" => "Glass",
                "marketPrice" => 3,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 19,
                "name" => "Plastic",
                "marketPrice" => 95,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 20,
                "name" => "Steel",
                "marketPrice" => 100,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 21,
                "name" => "Gas",
                "marketPrice" => 12.5,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 22,
                "name" => "Copper",
                "marketPrice" => 40,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 23,
                "name" => "Fabric",
                "marketPrice" => 1.5,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 24,
                "name" => "Titanium",
                "marketPrice" => 120,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 25,
                "name" => "Concrete",
                "marketPrice" => 2,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 26,
                "name" => "Treated Wood",
                "marketPrice" => 7,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 27,
                "name" => "Lapis Lazuli",
                "marketPrice" => 450,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 28,
                "name" => "Plutonium",
                "marketPrice" => 500,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 29,
                "name" => "Osmium",
                "marketPrice" => 350,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 30,
                "name" => "Reinforced Concrete",
                "marketPrice" => 65,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ],
            [
                "id" => 31,
                "name" => "Stable Anti-atom",
                "marketPrice" => 3500000,
                "levelToMine" => null,
                "timeToMine" => null,
                "mineQuantity" => null,
            ]
        ]);
    }
}
